# copy_dir.yml

- name: copy module for directories
  hosts: {{hosts}}
  connection: local
  tasks:
    - name: copy dir1 to /tmp
      copy:
        src: {{source}}
        dest: {{dest}}
        directory_mode:
      tags:
        - parentdir