- name: Ansible Copy Directory Example Local to Remote
- hosts: "{{ myhosts }}"  
  tasks:       
    - name:  Copying the Directory's contents (sub directories/files)
      copy:
        src: "{{ source }}"
        dest: "{{ dest }}" 
        mode: '0644'                                                                                       
        owner: root                                                                                        
        group: root
        force: yes
      become: true
      register: copy_out
